<?php
declare(strict_types=1);
namespace Liberu\Accounting\FinancialStatementsApi\Http\Controllers;
use Illuminate\Http\Request; use Illuminate\Routing\Controller; use Illuminate\Support\Facades\Gate; use Illuminate\Validation\ValidationException; use Liberu\Accounting\FinancialStatements\Queries\StatementQuery;
final class FinancialStatementsController extends Controller {
 private function input(Request $request):array{return $request->validate(['book_id'=>['required','integer'],'start_date'=>['required','date'],'end_date'=>['required','date','after_or_equal:start_date'],'dimensions'=>['nullable','array']]);}
 public function profitAndLoss(Request $request,StatementQuery $query){Gate::authorize('accounting.financial-statements.view');$data=$this->input($request);return response()->json(['data'=>$query->profitAndLoss($data['book_id'],$data['start_date'],$data['end_date'],$data['dimensions']??null)]);}
 public function balanceSheet(Request $request,StatementQuery $query){Gate::authorize('accounting.financial-statements.view');$data=$request->validate(['book_id'=>['required','integer'],'as_of_date'=>['required','date'],'dimensions'=>['nullable','array']]);return response()->json(['data'=>$query->balanceSheet($data['book_id'],$data['as_of_date'],$data['dimensions']??null)]);}
 public function cashFlow(Request $request,StatementQuery $query){Gate::authorize('accounting.financial-statements.view');$data=$this->input($request);return response()->json(['data'=>$query->cashFlow($data['book_id'],$data['start_date'],$data['end_date'])]);}
 public function equity(Request $request,StatementQuery $query){Gate::authorize('accounting.financial-statements.view');$data=$this->input($request);return response()->json(['data'=>$query->changesInEquity($data['book_id'],$data['start_date'],$data['end_date'])]);}
 public function comparative(Request $request,StatementQuery $query){Gate::authorize('accounting.financial-statements.view');$data=$request->validate(['book_id'=>['required','integer'],'start_date'=>['required','date'],'end_date'=>['required','date'],'comparative_start_date'=>['required','date'],'comparative_end_date'=>['required','date']]);return response()->json(['data'=>$query->comparative($data['book_id'],$data['start_date'],$data['end_date'],$data['comparative_start_date'],$data['comparative_end_date'])]);}
 public function drillThrough(Request $request,StatementQuery $query){Gate::authorize('accounting.financial-statements.view');$data=$request->validate(['book_id'=>['required','integer'],'account_id'=>['required','integer'],'start_date'=>['required','date'],'end_date'=>['required','date'],'dimensions'=>['nullable','array']]);return response()->json(['data'=>$query->drillThrough($data['book_id'],$data['account_id'],$data['start_date'],$data['end_date'],$data['dimensions']??null)]);}
}
