<?php
declare(strict_types=1);
namespace Liberu\Accounting\FinancialStatements\Queries;
use Illuminate\Support\Facades\DB;
use Liberu\Accounting\FinancialStatements\Exceptions\InvalidStatementRequest;
final class StatementQuery {
    private function lines(int $bookId,string $end,?string $start=null,?array $dimensions=null){$query=DB::table('accounting_journal_lines as l')->join('accounting_journal_entries as j','j.id','=','l.journal_entry_id')->join('accounting_chart_accounts as a','a.id','=','l.account_id')->where('j.book_id',$bookId)->where('j.status','posted')->whereDate('j.entry_date','<=',$end)->when($start,fn($q)=>$q->whereDate('j.entry_date','>=',$start))->when($dimensions,fn($q)=>$q->where(function($inner)use($dimensions){foreach($dimensions as $key=>$value)$inner->whereJsonContains('l.dimensions->'.$key,$value);}));return $query;}
    private function accounts(int $bookId,string $end,?string $start=null,?array $types=null,?array $dimensions=null){return $this->lines($bookId,$end,$start,$dimensions)->when($types,fn($q)=>$q->whereIn('a.type',$types))->groupBy('a.id','a.code','a.name','a.type','a.normal_balance')->select('a.id','a.code','a.name','a.type','a.normal_balance',DB::raw('SUM(l.debit) as debits'),DB::raw('SUM(l.credit) as credits'))->get()->map(function($row){$debit=(float)$row->debits;$credit=(float)$row->credits;$balance=$row->normal_balance==='debit'?$debit-$credit:$credit-$debit;return ['account_id'=>$row->id,'code'=>$row->code,'name'=>$row->name,'type'=>$row->type,'debits'=>round($debit,2),'credits'=>round($credit,2),'balance'=>round($balance,2)];})->values()->all();}
    public function profitAndLoss(int $bookId,string $start,string $end,?array $dimensions=null):array{$rows=$this->accounts($bookId,$end,$start,['revenue','expense','cost_of_goods_sold'],$dimensions);$revenue=array_values(array_filter($rows,fn($r)=>$r['type']==='revenue'));$cogs=array_values(array_filter($rows,fn($r)=>$r['type']==='cost_of_goods_sold'));$expenses=array_values(array_filter($rows,fn($r)=>$r['type']==='expense'));$sum=fn($set)=>round(array_sum(array_column($set,'balance')),2);$totalRevenue=$sum($revenue);$totalCogs=abs($sum($cogs));$totalExpenses=abs($sum($expenses));return ['type'=>'profit_and_loss','period'=>['start_date'=>$start,'end_date'=>$end],'revenue'=>['accounts'=>$revenue,'total'=>$totalRevenue],'cost_of_goods_sold'=>['accounts'=>$cogs,'total'=>$totalCogs],'gross_profit'=>round($totalRevenue-$totalCogs,2),'expenses'=>['accounts'=>$expenses,'total'=>$totalExpenses],'net_income'=>round($totalRevenue-$totalCogs-$totalExpenses,2)];}
    public function balanceSheet(int $bookId,string $asOf,?array $dimensions=null):array{$rows=$this->accounts($bookId,$asOf,null,['asset','liability','equity','bank','cash','current_asset','fixed_asset','current_liability','long_term_liability'],$dimensions);$group=fn($types)=>array_values(array_filter($rows,fn($r)=>in_array($r['type'],$types,true)));$assets=$group(['asset','bank','cash','current_asset','fixed_asset']);$liabilities=$group(['liability','current_liability','long_term_liability']);$equity=$group(['equity']);$sum=fn($set)=>round(array_sum(array_column($set,'balance')),2);$retained=$this->profitAndLoss($bookId,'2000-01-01',$asOf,$dimensions)['net_income'];return ['type'=>'balance_sheet','as_of_date'=>$asOf,'assets'=>['accounts'=>$assets,'total'=>$sum($assets)],'liabilities'=>['accounts'=>$liabilities,'total'=>abs($sum($liabilities))],'equity'=>['accounts'=>$equity,'retained_earnings'=>$retained,'total'=>round($sum($equity)+$retained,2)],'total_liabilities_and_equity'=>round(abs($sum($liabilities))+$sum($equity)+$retained,2)];}
    public function cashFlow(int $bookId,string $start,string $end):array{$rows=$this->accounts($bookId,$end,$start);$cash=array_values(array_filter($rows,fn($r)=>in_array($r['type'],['asset','bank','cash','current_asset'],true)));$net=round(array_sum(array_column($cash,'balance')),2);return ['type'=>'cash_flow','period'=>['start_date'=>$start,'end_date'=>$end],'operating_activities'=>['accounts'=>$cash,'net_cash_from_operations'=>$net],'investing_activities'=>['accounts'=>[],'net_cash_from_investing'=>0.0],'financing_activities'=>['accounts'=>[],'net_cash_from_financing'=>0.0],'net_change_in_cash'=>$net,'beginning_cash'=>0.0,'ending_cash'=>$net];}
    public function changesInEquity(int $bookId,string $start,string $end):array{$rows=$this->accounts($bookId,$end,$start,['equity']);$net=$this->profitAndLoss($bookId,$start,$end)['net_income'];return ['type'=>'changes_in_equity','period'=>['start_date'=>$start,'end_date'=>$end],'accounts'=>$rows,'net_income'=>$net,'total_change'=>round(array_sum(array_column($rows,'balance'))+$net,2)];}
    public function comparative(int $bookId,string $start,string $end,string $compareStart,string $compareEnd):array{return ['current'=>$this->profitAndLoss($bookId,$start,$end),'comparative'=>$this->profitAndLoss($bookId,$compareStart,$compareEnd)];}
    public function drillThrough(int $bookId,int $accountId,string $start,string $end,?array $dimensions=null):array{return $this->lines($bookId,$end,$start,$dimensions)->where('a.id',$accountId)->orderBy('j.entry_date')->select('j.id as journal_id','j.entry_number','j.entry_date','j.description','l.debit','l.credit','l.description as line_description','l.dimensions')->get()->map(fn($row)=>(array)$row)->all();}
}
