apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounting-erp-storage
  namespace: accounting-erp-laravel
  labels:
    app: accounting-erp-laravel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
